apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synesis-webui

resources:
  - namespace.yaml
  - webui-api-key-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - network-policy.yaml
  - secret-copy-job.yaml
