apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: synesis-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/part-of: synesis
    app.kubernetes.io/component: webui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: open-webui
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
