apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synesis-rag

resources:
  - job.yaml
  - cronjob.yaml

configMapGenerator:
  - name: domain-indexer-sources
    files:
      - sources.yaml
    options:
      disableNameSuffixHash: true
