apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synesis-models

labels:
  - pairs:
      app.kubernetes.io/part-of: synesis
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - model-storage-secret.yaml
  - qwen-coder-serving-runtime.yaml
  - qwen-coder-inference-service.yaml
  - mistral-nemo-serving-runtime.yaml
  - mistral-nemo-inference-service.yaml
