apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: synesis
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - service-monitor.yaml
  - grafana-dashboard.yaml
