apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synesis-search

labels:
  - pairs:
      app.kubernetes.io/part-of: synesis
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap-settings.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
