apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: synesis-search
  labels:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: synesis
    app.kubernetes.io/component: search
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: searxng
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
