apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synesis-gateway

labels:
  - pairs:
      app.kubernetes.io/part-of: synesis
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - litellm-secrets.yaml
  - litellm-config.yaml
  - litellm-deployment.yaml
  - litellm-service.yaml
  - litellm-route.yaml
