apiVersion: v1
kind: Service
metadata:
  name: synesis-planner
  namespace: synesis-planner
  labels:
    app.kubernetes.io/name: synesis-planner
    app.kubernetes.io/part-of: synesis
    app.kubernetes.io/component: planner
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: synesis-planner
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
